import {
  articleSlice,
  counterSlice,
  roleSlice,
  userSlice,
  tagSlice,
  categorySlice,
  subjectSlice,
  courseSlice,
  moduleSlice,
  chapterSlice,
  questionSlice,
  commentSlice,
  documentSlice,
  testimonialSlice,
  tweetSlice,
  eventSlice,
  certificateSlice,
  collaboratorSlice,
  serviceSlice,
} from "./slices";

export const reducer = {
  counter: counterSlice.reducer,
  article: articleSlice.reducer,
  user: userSlice.reducer,
  role: roleSlice.reducer,
  tag: tagSlice.reducer,
  category: categorySlice.reducer,
  subject: subjectSlice.reducer,
  course: courseSlice.reducer,
  module: moduleSlice.reducer,
  chapter: chapterSlice.reducer,
  question: questionSlice.reducer,
  comment: commentSlice.reducer,
  testimonial: testimonialSlice.reducer,
  tweet: tweetSlice.reducer,
  document: documentSlice.reducer,
  event: eventSlice.reducer,
  certificate: certificateSlice.reducer,
  collaborator: collaboratorSlice.reducer,
  service: serviceSlice.reducer,
};
